@startuml uml-deployment-notation
!theme plain
skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam DefaultFontName Manrope
skinparam DefaultFontSize 12
skinparam ArrowColor #475569
skinparam NodeBorderColor #1d4ed8
skinparam NodeBackgroundColor #eff6ff
skinparam ArtifactBorderColor #b45309
skinparam ArtifactBackgroundColor #fef3c7

title Anatomia da notação UML de Deployment

node "Smartphone <<device>>" as Phone #fdf2f8 {
  node "iOS 17 · App Sandbox\n<<executionEnvironment>>" as iOS {
    artifact "NetflixApp.ipa\nv8.42.0" as App
  }
}

node "EC2 Instance <<node>>" as EC2 {
  node "Docker\n<<executionEnvironment>>" as Docker {
    artifact "api:v3.2\nimage" as Api
  }
}

Phone --> EC2 : <<HTTPS>>

note bottom of Phone
  caixa 3D = node físico
end note

@enduml
