@startuml tutorial-01-hello
!theme plain
skinparam backgroundColor #FFFFFF
skinparam componentStyle uml2
skinparam shadowing false
skinparam DefaultFontName Manrope
skinparam DefaultFontSize 12
skinparam ArrowColor #475569

component "Frontend Web"  as FE
component "Backend API"   as BE
database  "PostgreSQL"    as DB

FE --( BE : IRest
BE --( DB : ISQL
@enduml
