@startuml tutorial-02-external
!theme plain
skinparam backgroundColor #FFFFFF
skinparam componentStyle uml2
skinparam shadowing false
skinparam DefaultFontName Manrope
skinparam DefaultFontSize 12
skinparam ArrowColor #475569

package "Parceiro de Mercado · Interno" {
  component "Frontend Web"   as FE
  component "Backend API"    as BE
  database  "PostgreSQL"     as DB
}

cloud "Serviços Externos" {
  component "Stripe API"     as Stripe
  component "SendGrid"       as Mail
  component "Google Maps"    as Maps
}

FE --( BE     : IRest
BE --( DB     : ISQL
BE --( Stripe : IPayment
BE --( Mail   : IMail
BE --( Maps   : IGeo

note right of Stripe
  «external»
  cobrança recorrente
end note
@enduml
